export default {
  PLACEHOLDER: {
    type: 'icon',
    icon: 'question',
    iconType: 'AntDesign',
    group: 'category',
  },
  CREDIT_CARD: {
    type: 'icon',
    icon: 'creditcard',
    iconType: 'AntDesign',
    group: 'category',
  },
  BOOK: {
    type: 'icon',
    icon: 'book',
    iconType: 'AntDesign',
    group: 'category',
  },
  MAIL: {
    type: 'icon',
    icon: 'mail',
    iconType: 'AntDesign',
    group: 'category',
  },
  HOME: {
    type: 'icon',
    icon: 'home',
    iconType: 'AntDesign',
    group: 'category',
  },
  SHOPPING_CART: {
    type: 'icon',
    icon: 'shoppingcart',
    iconType: 'AntDesign',
    group: 'category',
  },
  PHONE: {
    type: 'icon',
    icon: 'phone',
    iconType: 'AntDesign',
    group: 'category',
  },
  LINE_CHART: {
    type: 'icon',
    icon: 'linechart',
    iconType: 'AntDesign',
    group: 'category',
  },
  DESKTOP: {
    type: 'icon',
    icon: 'iconfontdesktop',
    iconType: 'AntDesign',
    group: 'category',
  },
  MOBILE: {
    type: 'icon',
    icon: 'mobile1',
    iconType: 'AntDesign',
    group: 'category',
  },
  KEY: {
    type: 'icon',
    icon: 'key',
    iconType: 'AntDesign',
    group: 'category',
  },
  TOOL: {
    type: 'icon',
    icon: 'tool',
    iconType: 'AntDesign',
    group: 'category',
  },
  SKIN: {
    type: 'icon',
    icon: 'skin',
    iconType: 'AntDesign',
    group: 'category',
  },
  CAR: {
    type: 'icon',
    icon: 'car',
    iconType: 'AntDesign',
    group: 'category',
  },
  ISV: {
    type: 'icon',
    icon: 'isv',
    iconType: 'AntDesign',
    group: 'category',
  },
  GIFT: {
    type: 'icon',
    icon: 'gift',
    iconType: 'AntDesign',
    group: 'category',
  },
  MEDICINE_BOX: {
    type: 'icon',
    icon: 'medicinebox',
    iconType: 'AntDesign',
    group: 'category',
  },
  REST: {
    type: 'icon',
    icon: 'rest',
    iconType: 'AntDesign',
    group: 'category',
  },
  WALLET: {
    type: 'icon',
    icon: 'wallet',
    iconType: 'AntDesign',
    group: 'category',
  },
  BANK: {
    type: 'icon',
    icon: 'bank',
    iconType: 'AntDesign',
    group: 'category',
  },
  BULB: {
    type: 'icon',
    icon: 'bulb1',
    iconType: 'AntDesign',
    group: 'category',
  },
  WIFI: {
    type: 'icon',
    icon: 'wifi',
    iconType: 'AntDesign',
    group: 'category',
  },
  AWARD: {
    type: 'icon',
    icon: 'award',
    iconType: 'Feather',
    group: 'category',
  },
  BRIEFCASE: {
    type: 'icon',
    icon: 'briefcase',
    iconType: 'Feather',
    group: 'category',
  },
  FILM: {
    type: 'icon',
    icon: 'film',
    iconType: 'Feather',
    group: 'category',
  },
  HEADPHONES: {
    type: 'icon',
    icon: 'headphones',
    iconType: 'Feather',
    group: 'category',
  },
  MAP: {
    type: 'icon',
    icon: 'map',
    iconType: 'Feather',
    group: 'category',
  },
  MUSIC: {
    type: 'icon',
    icon: 'music',
    iconType: 'Feather',
    group: 'category',
  },
  PACKAGE: {
    type: 'icon',
    icon: 'package',
    iconType: 'Feather',
    group: 'category',
  },
  TRUCK: {
    type: 'icon',
    icon: 'truck',
    iconType: 'Feather',
    group: 'category',
  },
  WATCH: {
    type: 'icon',
    icon: 'watch',
    iconType: 'Feather',
    group: 'category',
  },
  BICYCLE: {
    type: 'icon',
    icon: 'ios-bicycle',
    iconType: 'Ionicons',
    group: 'category',
  },
  BUS: {
    type: 'icon',
    icon: 'ios-bus',
    iconType: 'Ionicons',
    group: 'category',
  },
  WINE: {
    type: 'icon',
    icon: 'ios-wine',
    iconType: 'Ionicons',
    group: 'category',
  },
  BANK_TRANSFER: {
    type: 'icon',
    icon: 'bank-transfer',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  BANK_TRANSFER_IN: {
    type: 'icon',
    icon: 'bank-transfer-in',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  BANK_REMOVE: {
    type: 'icon',
    icon: 'bank-remove',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  BANK_PLUS: {
    type: 'icon',
    icon: 'bank-plus',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  BANK_MINUS: {
    type: 'icon',
    icon: 'bank-minus',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  BANK: {
    type: 'icon',
    icon: 'bank',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  CAR_SPORTS: {
    type: 'icon',
    icon: 'car-sports',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  CONTROLLER_CLASSIC: {
    type: 'icon',
    icon: 'controller-classic-outline',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  CUBE_OUTLINE: {
    type: 'icon',
    icon: 'cube-outline',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  DELETE_OUTLINE: {
    type: 'icon',
    icon: 'delete-outline',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  DOG_SIDE: {
    type: 'icon',
    icon: 'dog-side',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  HAMBURGER: {
    type: 'icon',
    icon: 'hamburger',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  HOSPITAL: {
    type: 'icon',
    icon: 'hospital',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  MOVIE_OUTLINE: {
    type: 'icon',
    icon: 'movie-outline',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  PAPERCLIP: {
    type: 'icon',
    icon: 'paperclip',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  RECEIPT: {
    type: 'icon',
    icon: 'receipt',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  STORE: {
    type: 'icon',
    icon: 'store',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  TRAIN: {
    type: 'icon',
    icon: 'train',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  TROPHY_OUTLINE: {
    type: 'icon',
    icon: 'trophy-outline',
    iconType: 'MaterialCommunityIcons',
    group: 'category',
  },
  ENERGY: {
    type: 'icon',
    icon: 'energy',
    iconType: 'SimpleLineIcons',
    group: 'category',
  },
  GAME_CONTROLLER: {
    type: 'icon',
    icon: 'game-controller',
    iconType: 'SimpleLineIcons',
    group: 'category',
  },
  PERCENT: {
    type: 'icon',
    icon: 'percent',
    iconType: 'Feather',
    group: 'category',
  },
  MONEY: {
    type: 'icon',
    icon: 'money',
    iconType: 'FontAwesome',
    group: 'category',
  },
  ALLAHABAD_BANK: {
    image: require('Src/assets/icons/allahabad-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  AMAZON_PAY: {
    image: require('Src/assets/icons/amazon-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  ANDHRA_BANK: {
    image: require('Src/assets/icons/andhra-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  AXIS_BANK: {
    image: require('Src/assets/icons/axis-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  BANK_OF_BARODA: {
    image: require('Src/assets/icons/bob-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  CANERA_BANK: {
    image: require('Src/assets/icons/canara-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  CENTRAL_BANK: {
    image: require('Src/assets/icons/central-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  CITY_BANK: {
    image: require('Src/assets/icons/city-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  FREECHARGE_BANK: {
    image: require('Src/assets/icons/freecharge-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  HDFC_BANK: {
    image: require('Src/assets/icons/hdfc-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  HDBC_BANK: {
    image: require('Src/assets/icons/hsbc-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  ICICI_BANK: {
    image: require('Src/assets/icons/icici-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  IDBI_BANK: {
    image: require('Src/assets/icons/IDBI-Bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  INDUS_BANK: {
    image: require('Src/assets/icons/indusind-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  KOTAK_BANK: {
    image: require('Src/assets/icons/kotak-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  MOBIKWIK: {
    image: require('Src/assets/icons/mobikwik-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  PAYTM_PAY: {
    image: require('Src/assets/icons/paytm-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  PNB_PAY: {
    image: require('Src/assets/icons/pnb-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  RBL_PAY: {
    image: require('Src/assets/icons/rbl-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  SBI_BANK: {
    image: require('Src/assets/icons/sbi-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  UNION_BANK: {
    image: require('Src/assets/icons/union-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
  YES_BANK: {
    image: require('Src/assets/icons/yes-bank.jpg'),
    group: 'Wallet',
    type: "image",
  },
};
